workflows:
  ios-release:
    name: Flutter iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      groups:
        - ios_signing

    ios_signing:
      distribution_type: app_store
      bundle_identifier: com.rx4digital.storyapp
      apple_id: $APPLE_ID
      app_store_connect_issuer_id: $APP_STORE_ISSUER_ID
      app_store_connect_key_identifier: $APP_STORE_KEY_ID
      app_store_connect_private_key: $APP_STORE_PRIVATE_KEY

    scripts:
      - name: Build IPA
        script: |
          flutter pub get
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
