workflows:
  ios-release:
    name: Flutter iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest

    ios_signing:
      distribution_type: app_store
      bundle_identifier: com.rx4digital.storyapp

    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles

      - name: Install dependencies
        script: |
          flutter pub get

      - name: Build iOS (IPA assinado)
        script: |
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        api_key_path: $APP_STORE_CONNECT_API_KEY     # Caminho do arquivo .p8
        submit_to_testflight: true
        submit_to_app_store: false
