workflows:
  ios-release:
    name: Flutter iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: "14.3.1"
      vars:
        BUNDLE_ID: com.rx4digital.storyapp
      groups:
        - ios_signing

    scripts:
      - name: Set up keychain
        script: |
          keychain initialize

      - name: Fetch signing files from App Store Connect
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

      - name: Add certificates to keychain
        script: |
          keychain add-certificates

      - name: Use provisioning profiles in Xcode project
        script: |
          xcode-project use-profiles

      - name: Flutter build IPA
        script: |
          flutter pub get
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID

        submit_to_testflight: true
        expire_build_submitted_for_review: true
